// This file is automatically generated. Keep environment access centralized in src/config/environment.ts.
import {
  isSupabaseBackendEnabled,
  requireSupabaseEnvironment,
} from "@/config/environment";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { withLaje87RpcCompatibility } from "./laje87RpcCompatibility";
import type { Database } from "./types";

type LajeSupabaseClient = SupabaseClient<Database>;

function createDisabledSupabaseClient(): LajeSupabaseClient {
  return new Proxy({} as LajeSupabaseClient, {
    get(_target, property) {
      if (property === "then") {
        return undefined;
      }

      throw new Error(
        `Supabase está desabilitado neste deployment AWS. Acesso solicitado: ${String(property)}. Migre o fluxo para a laje-api ou desabilite-o explicitamente até a tarefa responsável ser concluída.`,
      );
    },
  });
}

function createLajeSupabaseClient(): LajeSupabaseClient {
  if (!isSupabaseBackendEnabled()) {
    return createDisabledSupabaseClient();
  }

  const { supabaseUrl, supabasePublishableKey } = requireSupabaseEnvironment();

  const rawSupabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return withLaje87RpcCompatibility(rawSupabase);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// Em deployments AWS-only este objeto é um guard explícito e não inicializa
// @supabase/supabase-js. Qualquer acesso legado residual falha de forma clara.
export const supabase = createLajeSupabaseClient();
