// This file is automatically generated. Keep environment access centralized in src/config/environment.ts.
import { requireSupabaseEnvironment } from "@/config/environment";
import { createClient } from "@supabase/supabase-js";
import { withLaje87RpcCompatibility } from "./laje87RpcCompatibility";
import type { Database } from "./types";

const { supabaseUrl, supabasePublishableKey } = requireSupabaseEnvironment();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const rawSupabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const supabase = withLaje87RpcCompatibility(rawSupabase);
