// This file is automatically generated. Keep environment access centralized in src/config/environment.ts.
import { requireSupabaseEnvironment } from "@/config/environment";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const { supabaseUrl, supabasePublishableKey } = requireSupabaseEnvironment();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
